export const primaryColor = '#109724'
export const backgroundColor = '#FAEFE3'
export const backgroundSecondaryColor = '#FFF8F1'
export const placeholderTextColor = '#CEC0AF'
export const playerBackgroundColor = '#FFF8F1'
export const secondaryColor = '#EEE1D2'
export const textCaptionColor = '#908579'
export const textDarkColor = '#02294C'