export const primaryColor = '#109724'
export const yellowColor = '#FEC200'
export const navyColor = '#02294C'
export const beigeColor = '#D8B275'
export const PlumColor = '#8A3A49'
export const BlueColor = '#2753D2'
export const redColor = '#FF4800'

export const BeigeFirstColor = '#FFF8F1'
export const BeigeSecondColor = '#FAEFE3'
export const BeigeThirdColor = '#EEE1D2'
export const BeigeForthColor = '#CEC0AF'
export const BeigeFifthColor = '#908579'
export const BeigeSixthColor = '#54412B'